name: Auto Commit CSV Changes

on:
  push:
    paths:
      - '**/*.csv'  # This will watch for any CSV file changes in any directory
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
      - name: Commit and Push CSV changes
        run: |
          echo "Checking for CSV changes..."
          git add "**/*.csv"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-update CSV file [skip ci]"
            git push
          fi 