name: Update CSV

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  update-csv:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy CSV
      shell: pwsh
      run: |
        Copy-Item "J:\Unorganized\vhs_transfers.csv" "public/vhs_transfers.csv"
        
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/vhs_transfers.csv
        git commit -m "Update CSV" || exit 0
        git push